galaxy_info:
  author: Josh Swanson, Derek Winters 
  description: Configure a Satellite Capsules
  license: license GPL-2.0
  min_ansible_version: 2.9
  galaxy_tags:
    - satellite6
    - configure_satellite
    - configure_capsule

dependencies: []
